version: "3.8"

services:
  nginx:
    image: nginx:1.26.0
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/php
      dockerfile: dockerfile
    volumes:
      - ./src:/var/www

  mysql:
    image: mysql:8.0.37
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"


  phpmyadmin:
    image: phpmyadmin
    environment:
      # - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8888:80"
    depends_on:
      - mysql